import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../style/textAnimation.css";
import "../style/theme.css";
import "../style/style.css";
import StoreProvider from "../utils/store";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// style={{borderBottom: 'rgba(253, 21, 21, 0.1)', borderBlock: 'solid'}}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // console.log(localStorage.getItem("theme") || "")

  // useEffect(() => {
  //   let whatTheme = localStorage.getItem("theme") || "";  
  //   // setCheckTheme(whatTheme)
  //   console.log(whatTheme)
  // // checkTheme == 'dark' ? activateDark() : activateLight()
  
  // }, []);  

  
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} `}>{children}</body>
      </html>
    </StoreProvider>
  );
}
